/* File: _data/news_helper.js */
const fs = require("fs");
const path = require("path");

module.exports = function() {
  const sourceDataFile = path.join(__dirname, "../data/market_news.json");
  
  if (!fs.existsSync(sourceDataFile)) {
    console.log("⚠️ Warning: data/market_news.json source payload not found during build sequence.");
    return [];
  }
  
  // Read the chronological Pacific Time feed generated by the python harvest script
  const rawPayload = JSON.parse(fs.readFileSync(sourceDataFile, "utf8"));
  
  // Strict multi-route tracking configuration blueprint mapping to your 8 public URLs
  const routerConfiguration = [
    { name: "All News", slug: "", filterKey: "all" },
    { name: "Real Estate", slug: "real-estate", filterKey: "real-estate" },
    { name: "Business", slug: "business", filterKey: "business" },
    { name: "North Sound", slug: "north-sound", filterKey: "north-sound" },
    { name: "Seattle", slug: "seattle", filterKey: "seattle" },
    { name: "Eastside", slug: "eastside", filterKey: "eastside" },
    { name: "Snohomish County", slug: "snohomish-county", filterKey: "snohomish-county" },
    { name: "South King", slug: "south-king", filterKey: "south-king" }
  ];

  return routerConfiguration.map(route => {
    let categorizedStories = [];
    
    // Evaluate the input array elements using clear list inclusion parameters
    if (route.filterKey === "all") {
      categorizedStories = rawPayload;
    } else if (route.filterKey === "snohomish-county") {
      // 🌟 DUAL-TAGGING OVERLAP POLICY: Automatically include North Sound stories in Snohomish County loops
      categorizedStories = rawPayload.filter(story => 
        story.categories && (story.categories.includes("snohomish-county") || story.categories.includes("north-sound"))
      );
    } else {
      // General Case: Search inside the categories array for the matching lowercase slug identifier
      categorizedStories = rawPayload.filter(story => 
        story.categories && story.categories.includes(route.filterKey)
      );
    }

    // Capture the top 50 strictly sorted stories for the active page layout
    const slice50 = categorizedStories.slice(0, 50);

    const dynamicCities = new Set();
    const dynamicSources = new Set();

    // Scan the active story array to dynamically populate the refinement switchdeck options
    slice50.forEach(story => {
      if (story.source) {
        dynamicSources.add(story.source);
      }
      if (story.cities && story.cities.length > 0) {
        story.cities.forEach(city => {
          if (city) dynamicCities.add(city);
        });
      }
    });

    // Output parameters match the properties your page markup expects
    return {
      subCategoryName: route.name,
      activeFilter: route.filterKey,
      permalinkPath: route.slug ? `news/${route.slug}/index.html` : "news/index.html",
      articles: slice50,
      tabs: routerConfiguration,
      sidebarCities: Array.from(dynamicCities).sort(),
      sidebarSources: Array.from(dynamicSources).sort()
    };
  });
};